Handle both master and main

diff --git a/bin/git-changed-files b/bin/git-changed-files
--- a/bin/git-changed-files
+++ b/bin/git-changed-files
@@ -2,8 +2,28 @@
 
 set -e
 
+git_branch_exists() {
+  git rev-parse "$1" 1>/dev/null 2>/dev/null
+}
+
+branch() {
+  if git_branch_exists "master"; then
+    echo "master"
+  elif git_branch_exists "main"; then
+    echo "main"
+  else
+    echo >&1 "Could not find a master or main branch"
+    exit 1
+  fi
+}
+
 if [ -n "$(git status --porcelain)" ]; then
   git status --porcelain | cut -c 4-
 else
-  git diff origin/master..HEAD --name-status --diff-filter=d | rev | cut -f 1 | rev
+  git diff origin/$(branch)..HEAD \
+    --name-status \
+    --diff-filter=d \
+    | rev \
+    | cut -f 1 \
+    | rev
 fi
diff --git a/bin/git-fixup b/bin/git-fixup
--- a/bin/git-fixup
+++ b/bin/git-fixup
@@ -7,11 +7,26 @@ command -v fzf >/dev/null 2>&1 || {
   exit 1
 }
 
+git_branch_exists() {
+  git rev-parse "$1" 1>/dev/null 2>/dev/null
+}
+
+branch() {
+  if git_branch_exists "master"; then
+    echo "master"
+  elif git_branch_exists "main"; then
+    echo "main"
+  else
+    echo >&1 "Could not find a master or main branch"
+    exit 1
+  fi
+}
+
 if [ -n "$1" ]; then
   git commit --fixup="$1"
 else
   git commit --fixup="$( \
-    git log --oneline origin/master.. | \
+    git log --oneline origin/$(branch).. | \
     fzf | \
     cut -d" " -f1 \
     )"
diff --git a/bin/git-recent b/bin/git-recent
--- a/bin/git-recent
+++ b/bin/git-recent
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # `git-recent` logs local and unpushed commits if there are any. If not, it logs
-# the local tree against `origin/master`.
+# the local tree against `origin/{master,main}`.
 
 set -e
 
@@ -23,10 +23,25 @@ has_unpulled_commits() {
   [ "$(git_log 'HEAD..@{upstream}' | wc -l)" -gt 0 ]
 }
 
+git_branch_exists() {
+  git rev-parse "$1" 1>/dev/null 2>/dev/null
+}
+
+branch() {
+  if git_branch_exists "master"; then
+    echo "master"
+  elif git_branch_exists "main"; then
+    echo "main"
+  else
+    echo >&1 "Could not find a master or main branch"
+    exit 1
+  fi
+}
+
 if has_upstream && has_local_commits; then
   git_log "@{upstream}..HEAD" "$@"
 elif has_upstream && has_unpulled_commits; then
   git_log "HEAD..@{upstream}" "$@"
 else
-  git_log "origin/master..HEAD" "$@"
+  git_log "origin/$(branch)..HEAD" "$@"
 fi
